---
services:
  zookeeper:
    image: 'cr.yandex/crp9q9dbm5n3ipl1neu3/zookeeper:latest'
    expose:
      - 2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: always
    networks:
      - internal

  kafka:
    image: 'cr.yandex/crp9q9dbm5n3ipl1neu3/kafka:3.2.3-debian-11-r52'
    expose:
      - 9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CREATE_TOPICS=currency-rates
    depends_on:
      - zookeeper
    restart: always
    networks:
      - internal

  postgres:
    image: 'cr.yandex/crp9q9dbm5n3ipl1neu3/postgres:15.0-alpine'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    expose:
      - 5432
    restart: always
    networks:
      - internal

  service:
    build: .
    env_file: .env
    depends_on:
      - postgres
      - kafka
    restart: always
    networks:
      - internal

  checker:
    image: 'cr.yandex/crp9q9dbm5n3ipl1neu3/checker:latest'
    environment:
      HOST: service
      PORT: 8080
      PROTOCOL: http
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      KAFKA_TOPIC: currency-rates
      TRACK: "${CI_PROJECT_NAME}"
      NICKNAME: "${CI_PROJECT_NAMESPACE}"
      COMMIT_TIMESTAMP: "${CI_COMMIT_TIMESTAMP}"
      SEED: "${SEED}"
    depends_on:
      - service
      - kafka
    networks:
      - internal

  perf-tester:
    image: 'cr.yandex/crp9q9dbm5n3ipl1neu3/perf-tester:latest'
    environment:
      HOST: service
      PORT: 8080
      TRACK: "${CI_PROJECT_NAME}"
      NICKNAME: "${CI_PROJECT_NAMESPACE}"
      CI_COMMIT_TIMESTAMP: "${CI_COMMIT_TIMESTAMP}"
      SEED: "${CI_JOB_STARTED_AT}"
    depends_on:
      - service
    networks:
      - internal

networks:
  internal:
